// AvalonInterface_register_file_0.v

// This file was auto-generated from register_file_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 22.1 917

`timescale 1 ps / 1 ps
module AvalonInterface_register_file_0 (
		input  wire [7:0]  avs_s0_address,     // avs_s0.address
		input  wire        avs_s0_read,        //       .read
		output wire [31:0] avs_s0_readdata,    //       .readdata
		input  wire        avs_s0_write,       //       .write
		input  wire [31:0] avs_s0_writedata,   //       .writedata
		output wire        avs_s0_waitrequest, //       .waitrequest
		input  wire        clock_clk,          //  clock.clk
		input  wire        reset_reset         //  reset.reset_n
	);

	AvalonInterface_register_file_0 register_file_0 (
		.avs_s0_address     (avs_s0_address),     // avs_s0.address
		.avs_s0_read        (avs_s0_read),        //       .read
		.avs_s0_readdata    (avs_s0_readdata),    //       .readdata
		.avs_s0_write       (avs_s0_write),       //       .write
		.avs_s0_writedata   (avs_s0_writedata),   //       .writedata
		.avs_s0_waitrequest (avs_s0_waitrequest), //       .waitrequest
		.clock_clk          (clock_clk),          //  clock.clk
		.reset_reset        (reset_reset)         //  reset.reset_n
	);

endmodule
